spring.application.name=servicio-pedidos

server.port=8081

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fastflow_pedidos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Evita consultas innecesarias desde controladores
spring.jpa.open-in-view=false

# Zona horaria
spring.jackson.time-zone=Europe/Madrid
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Madrid
# Logs Hibernate desactivados
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF